### ISSUE TITLE
IOC example that contains an Epics client?

### ISSUE THREAD

**Issue by rajanplumley** [caproto/caproto#579] opened 2020-04-01 22:47 UTC
Can an example be made that demonstrates how one might use an Epics client in conjunction with the caproto server to read and write to external PVs?

**Comment by tacaswell** [comment] 2020-04-01 23:09
The problem is that all of the IOCs are async based but the only clients we have finished writing are the threaded and sync clients.

I _think_ you can just use the threaded client in the IOC, but it would be much better to get the async clients written....

**Comment by danielballan** [comment] 2020-04-01 23:09
Hello, @rajanplumley! This is a good suggestion, one I think we can act on, though it raises an issue I will comment on at length below.

Ideally, one would use a single concurrency framework (threads, asycnio, trio, curio, etc.) for both the server and client aspects of the program. Unfortunately, our servers use asyncio or trio or curio, and our high-quality client uses threads. (We also have a synchronous client that is of high quality, but its synchronous nature makes it unsuitable for use inside a server.) Therefore, at the moment, such an example would have to use asyncio/trio/curio for the server and threads for the client aspects, which is a bit weird, but certainly workable. We have _sketches_ of trio and curio clients. In the future we hope to bring them up to the same level of quality as the threading-based client, and also to add an asyncio-based client.

All that said, a working server that uses the threading client inside would be useful as a stop-gap, even if it would be a bit of a Frankenstein.

**Comment by danielballan** [comment] 2020-04-01 23:09
Ha, _jinx_ @tacaswell. :-D

**Comment by rajanplumley** [comment] 2020-04-01 23:36
Thanks @danielballan and @tacaswell.  I'll experiment with using the threading client inside the server and report any surprises ;)

**Comment by klauer** [comment] 2020-08-01 19:10
Added the example, which is now merged. 
Hopefully we'll get to an asyncio client example one day soon as well.

**Closed by klauer** 2020-08-01 19:10 UTC
